--------------------------------------------------------
--  File created - Monday-January-28-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WORK
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."WORK" 
   (	"ID_OFFICE" NUMBER, 
	"ID_EMPLOYEE" NUMBER, 
	"ID_POSITION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OFFICE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."OFFICE" 
   (	"ID_OFFICE" NUMBER, 
	"ID_COMPANY" NUMBER, 
	"ID_ADDRESS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POSITION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."POSITION" 
   (	"ID_POSITION" NUMBER, 
	"POSITION_NAME" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYEE" 
   (	"ID_EMPLOYEE" NUMBER, 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"ID_ADDRESS" NUMBER, 
	"ADDRESS" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COUNTRY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COUNTRY" 
   (	"ID_COUNTRY" NUMBER, 
	"COUNTRY_NAME" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPANY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COMPANY" 
   (	"ID_COMPANY" NUMBER, 
	"COMPANY_NAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CITY" 
   (	"ID_CITY" NUMBER, 
	"CITY_NAME" VARCHAR2(50 BYTE), 
	"ID_COUNTRY" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"COUNTRY" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADDRESS" 
   (	"ID_ADDRESS" NUMBER, 
	"STREET" VARCHAR2(50 BYTE), 
	"BUILDING" NUMBER, 
	"APARTMENT" NUMBER, 
	"ID_CITY" NUMBER, 
	"CITY" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OFFICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."OFFICE_PK" ON "SYSTEM"."OFFICE" ("ID_OFFICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POSITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."POSITION_PK" ON "SYSTEM"."POSITION" ("ID_POSITION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLOYEE_PK" ON "SYSTEM"."EMPLOYEE" ("ID_EMPLOYEE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COUNTRY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."COUNTRY_PK" ON "SYSTEM"."COUNTRY" ("ID_COUNTRY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMPANY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."COMPANY_PK" ON "SYSTEM"."COMPANY" ("ID_COMPANY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CITY_PK" ON "SYSTEM"."CITY" ("ID_CITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ADDRESS_PK" ON "SYSTEM"."ADDRESS" ("ID_ADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table OFFICE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."OFFICE" ADD CONSTRAINT "OFFICE_PK" PRIMARY KEY ("ID_OFFICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."OFFICE" MODIFY ("ID_OFFICE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."OFFICE" MODIFY ("ID_COMPANY" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."OFFICE" MODIFY ("ID_ADDRESS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSITION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."POSITION" ADD CONSTRAINT "POSITION_PK" PRIMARY KEY ("ID_POSITION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."POSITION" MODIFY ("ID_POSITION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."POSITION" MODIFY ("POSITION_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID_EMPLOYEE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."EMPLOYEE" MODIFY ("ID_EMPLOYEE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE" MODIFY ("LASTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYEE" MODIFY ("ID_ADDRESS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COUNTRY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COUNTRY" ADD CONSTRAINT "COUNTRY_PK" PRIMARY KEY ("ID_COUNTRY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."COUNTRY" MODIFY ("ID_COUNTRY" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."COUNTRY" MODIFY ("COUNTRY_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPANY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COMPANY" ADD CONSTRAINT "COMPANY_PK" PRIMARY KEY ("ID_COMPANY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."COMPANY" MODIFY ("ID_COMPANY" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."COMPANY" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CITY" ADD CONSTRAINT "CITY_PK" PRIMARY KEY ("ID_CITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."CITY" MODIFY ("ID_CITY" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CITY" MODIFY ("CITY_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CITY" MODIFY ("ID_COUNTRY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADDRESS" ADD CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ID_ADDRESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."ADDRESS" MODIFY ("ID_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ADDRESS" MODIFY ("STREET" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ADDRESS" MODIFY ("BUILDING" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ADDRESS" MODIFY ("ID_CITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table WORK
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."WORK" ADD CONSTRAINT "FK28BF1156050887" FOREIGN KEY ("ID_OFFICE")
	  REFERENCES "SYSTEM"."OFFICE" ("ID_OFFICE") ENABLE;
 
  ALTER TABLE "SYSTEM"."WORK" ADD CONSTRAINT "FK28BF119D4535A1" FOREIGN KEY ("ID_POSITION")
	  REFERENCES "SYSTEM"."POSITION" ("ID_POSITION") ENABLE;
 
  ALTER TABLE "SYSTEM"."WORK" ADD CONSTRAINT "FK28BF11D265D0AB" FOREIGN KEY ("ID_EMPLOYEE")
	  REFERENCES "SYSTEM"."EMPLOYEE" ("ID_EMPLOYEE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OFFICE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."OFFICE" ADD CONSTRAINT "FK8ACA32BC94894FCB" FOREIGN KEY ("ID_COMPANY")
	  REFERENCES "SYSTEM"."COMPANY" ("ID_COMPANY") ENABLE;
 
  ALTER TABLE "SYSTEM"."OFFICE" ADD CONSTRAINT "FK8ACA32BC9A6A0EB9" FOREIGN KEY ("ID_ADDRESS")
	  REFERENCES "SYSTEM"."ADDRESS" ("ID_ADDRESS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_ID_ADDRESS_FK" FOREIGN KEY ("ID_ADDRESS")
	  REFERENCES "SYSTEM"."ADDRESS" ("ID_ADDRESS") ENABLE;
 
  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD CONSTRAINT "FK75C8D6AEF0FFA5DD" FOREIGN KEY ("ADDRESS")
	  REFERENCES "SYSTEM"."ADDRESS" ("ID_ADDRESS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CITY" ADD CONSTRAINT "FK1F916B956985FD" FOREIGN KEY ("ID_COUNTRY")
	  REFERENCES "SYSTEM"."COUNTRY" ("ID_COUNTRY") ENABLE;
 
  ALTER TABLE "SYSTEM"."CITY" ADD CONSTRAINT "FK1F916BEBFF1D21" FOREIGN KEY ("COUNTRY")
	  REFERENCES "SYSTEM"."COUNTRY" ("ID_COUNTRY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADDRESS" ADD CONSTRAINT "ADDRESS_FK" FOREIGN KEY ("ID_CITY")
	  REFERENCES "SYSTEM"."CITY" ("ID_CITY") ENABLE;
 
  ALTER TABLE "SYSTEM"."ADDRESS" ADD CONSTRAINT "FKE66327D4E09B9101" FOREIGN KEY ("CITY")
	  REFERENCES "SYSTEM"."CITY" ("ID_CITY") ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_OFFICE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."BI_OFFICE" 
  before insert on "OFFICE"               
  for each row  
begin   
    select "OFFICE_SEQ".nextval into :NEW.ID_OFFICE from dual; 
end; 

/
ALTER TRIGGER "SYSTEM"."BI_OFFICE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_POSITION
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."BI_POSITION" 
  before insert on "POSITION"               
  for each row  
begin   
    select "POSITION_SEQ".nextval into :NEW.ID_POSITION from dual; 
end; 

/
ALTER TRIGGER "SYSTEM"."BI_POSITION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_EMPLOYEE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."BI_EMPLOYEE" 
  before insert on "EMPLOYEE"               
  for each row  
begin   
    select "EMPLOYEE_SEQ".nextval into :NEW.ID_EMPLOYEE from dual; 
end; 

/
ALTER TRIGGER "SYSTEM"."BI_EMPLOYEE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_COUNTRY
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."BI_COUNTRY" 
  before insert on "COUNTRY"               
  for each row  
begin   
    select "COUNTRY_SEQ".nextval into :NEW.ID_COUNTRY from dual; 
end; 

/
ALTER TRIGGER "SYSTEM"."BI_COUNTRY" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_COMPANY
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."BI_COMPANY" 
  before insert on "COMPANY"               
  for each row  
begin   
    select "COMPANY_SEQ".nextval into :NEW.ID_COMPANY from dual; 
end; 

/
ALTER TRIGGER "SYSTEM"."BI_COMPANY" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_CITY
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."BI_CITY" 
  before insert on "CITY"               
  for each row  
begin   
    select "CITY_SEQ".nextval into :NEW.ID_CITY from dual; 
end; 

/
ALTER TRIGGER "SYSTEM"."BI_CITY" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_ADDRESS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."BI_ADDRESS" 
  before insert on "ADDRESS"               
  for each row  
begin   
    select "ADDRESS_SEQ".nextval into :NEW.ID_ADDRESS from dual; 
end; 

/
ALTER TRIGGER "SYSTEM"."BI_ADDRESS" ENABLE;
